Setup:
	zypper install -y gcc-c++
	zypper install -y gcc
	zypper install -y gdb
	zypper install -y cmake
	zypper install -y python3
	zypper install -y strace
	zypper install -y tree
	zypper install -y iputils
	zypper install -y net-tools
	zypper install -y net-tools-deprecated